### ISSUE TITLE
[0.2.0] after update icon gone

### ISSUE THREAD

**Issue by Nokius** [CODeRUS/splashscreen-changer#1]
After the update via warehouse the Icon for GUI is gone in launcher also there is no icon in Settings -> Apps

**Comment by CODeRUS** [comment]
Everything is good for me
![_ _20160924_001](https://cloud.githubusercontent.com/assets/720601/18807694/a92c63b0-8256-11e6-8c02-00ceb8344693.png)

**Comment by Nokius** [comment]
yes u are right just saw that 0.2.0 is now available via jolla-settings 

sorry
